# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis
        # Provide the password for postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install UV Package manager
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        working-directory: ./backend
        run: uv pip install -r requirements.txt --system

      - name: Install Ruff Linter
        working-directory: ./backend
        run: uv tool install ruff@latest

      - name: Run lint with Ruff
        working-directory: ./backend
        run: uvx ruff check

      - name: Create Database tables
        working-directory: ./backend
        env:
          ENVIRONMENT: TEST
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
          AWS_BUCKET: ${{ vars.AWS_BUCKET}}
          AWS_REGION: ${{ vars.AWS_REGION}}
          AWS_TOKEN: token
          TEST_DB_URL: "postgresql://admin:postgres@localhost:5432/test_db"

        run: python3 init_test_db.py

      - name: Test with pytest
        working-directory: ./backend
        env:
          ENVIRONMENT: TEST
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
          TEST_DB_URL: "postgresql://admin:postgres@localhost:5432/test_db"
          AWS_BUCKET: ${{ vars.AWS_BUCKET}}
          AWS_REGION: ${{ vars.AWS_REGION}}
          AWS_TOKEN: token

        run: export PYTHONPATH=/home/runner/work/Trailstory/Trailstory/backend:$PYTHONPATH && pytest
